# Generated by Django 5.1.3 on 2024-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_profile_phone_number_alter_trip_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="item_price",
            field=models.FloatField(),
        ),
    ]
