# Generated by Django 5.1.3 on 2024-12-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_cost_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="project.profile",
            ),
        ),
    ]
