# Generated by Django 5.1.3 on 2024-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_voter_voter_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="address_zip_code",
            field=models.TextField(),
        ),
    ]
