# Generated by Django 5.1.3 on 2024-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_address_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="address_apt_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="address_zip_code",
            field=models.IntegerField(),
        ),
    ]
