# Generated by Django 5.1.1 on 2024-10-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="titles",
            new_name="title",
        ),
    ]
